config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :students
  devise_for :teachers, controllers: { sessions: 'teachers/sessions' }
  devise_for :institutions


  resources :institutions, only: [:new, :create, :show, :edit, :update, :destroy]
  root to: "pages#home"


  resources :institutions do
    resources :subjects, only: [:new, :create]
    resources :teachers, only: [:new, :create]
    resources :students, only: [:new, :create]
  end



  # nesteado para rutas de take_quizzes de un quiz
  # el alumno no puede borrar, editar o un quiz
  resources :quizzes do
    resources :take_quizzes, only: [:new, :create]
    end

  resources :teachers, only: [:new, :create, :show] do
    resources :quizzes
  end

  resources :quizzes do
    resources :take_quizzes, only: [:new, :create]
  end

  resources :students do
    resources :student_subjects, only: [:new, :create]
  end

  resources :questions, only: [:index, :show]

  get 'quienes_somos', to: 'pages#quienes_somos'
  get 'preguntas_frecuentes', to: 'pages#preguntas_frecuentes'

end

app/views/shared/_footer.html.erb
<footer class="footer">
  <!-- Contenido del footer -->
</footer>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light fixed-top navbar-transparente">
    <div class="container">
      <%= link_to "/" do %>
        <%= image_tag("logo.png", width: 90) %>
      <% end %>

      <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
        <i class="fas fa-bars text-white"></i>
      </button>

      <div class="collapse navbar-collapse" id="nav-principal">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="/quienes_somos" class="nav-link">Quiénes Somos</a>
          </li>

            <li class="nav-item">
              <a href="/preguntas_frecuentes" class="nav-link">Preguntas Frecuentes</a>
            </li>

          <li class="nav-item divisor"></li>

          <% if student_signed_in? %>
            <li class="nav-item">
              <%= link_to "Cerrar Sesion", destroy_student_session_path, class: "nav-link", data: {turbo_method: :delete} %>
               <p class="text-primary nav-link"><%= current_student.name %></p>

            </li>
            <li class="nav-item">
              <%#= link_to "Editar Perfil", edit_student_registration_path, class: "nav-link" %>
            </li>
          <% elsif teacher_signed_in? %>
            <li class="nav-item">
                <%= link_to "Cerrar Sesion", destroy_teacher_session_path, class: "nav-link", data: {turbo_method: :delete} %>
               <p class="text-primary nav-link"><%= current_teacher.name %></p>


            </li>
            <li class="nav-item">
              <%#= link_to "Editar Perfil", edit_teacher_registration_path, class: "nav-link" %>
            </li>
          <% elsif institution_signed_in? %>
            <li class="nav-item">
              <%= link_to "Cerrar Sesion", destroy_institution_session_path, class: "nav-link", data: {turbo_method: :delete} %>
                <p class="text-primary nav-link"><%= current_institution.name %></p>

            </li>
            <li class="nav-item">
              <%#= link_to "Editar Perfil", edit_teacher_registration_path, class: "nav-link" %>
            </li>
          <% else %>

          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>