config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :students
  devise_for :teachers, controllers: { sessions: 'teachers/sessions' }
  devise_for :institutions


  resources :institutions, only: [:new, :create, :show, :edit, :update, :destroy]
  root to: "pages#home"


  resources :institutions do
    resources :subjects, only: [:new, :create]
    resources :teachers, only: [:new, :create]
    resources :students, only: [:new, :create]
  end



  # nesteado para rutas de take_quizzes de un quiz
  # el alumno no puede borrar, editar o un quiz
  resources :quizzes do
    resources :take_quizzes, only: [:new, :create]
    end

  resources :teachers, only: [:new, :create, :show] do
    resources :quizzes
  end

  resources :quizzes do
    resources :take_quizzes, only: [:new, :create]
  end

  resources :students do
    resources :student_subjects, only: [:new, :create]
  end

  resources :questions, only: [:index, :show]

  get 'quienes_somos', to: 'pages#quienes_somos'
  get 'preguntas_frecuentes', to: 'pages#preguntas_frecuentes'

end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :institution
  belongs_to :teacher
  has_many :student_subjects
  has_many :students, through: :student_subjects
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_institution, only: [:new, :create, :edit, :update, :destroy, :index]
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  def index
    @subjects = @institution.subjects
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    @subject.institution_id = @institution.id
    if @subject.save
      redirect_to @institution, notice: 'La materia ha sido creada de manera exitosa.'
    else
      render :new
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      redirect_to @institution, notice: 'La materia ha sido actualizada de manera exitosa.'
    else
      render :edit
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    redirect_to @institution, notice: 'La materia ha sido eliminada de manera exitosa.'
  end

  private

  def set_institution
    @institution = Institution.find(params[:institution_id])
  end

  def subject_params
    params.require(:subject).permit(:name, :teacher_id)
  end
end

app/views/subjects/edit.html.erb
<!-- app/views/subjects/edit.html.erb -->
<h1>Editar Materia</h1>
<div class="grid">
  <svg class="grid-svg" xmlns="http://www.w3.org/2000/svg" width="982" height="786" viewBox="0 0 982 786" fill="none">
    <!-- Tu contenido SVG aquí -->
  </svg>
  <div class="blur"></div>
</div>

<div class="form-containerslo">
  <div class="form-sectionslo" id="signup-section">

<%= form_with(model: [@institution, @subject], local: true) do |form| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> La materia no ha podido ser guardada </h2>

      <ul>
        <% @subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nombre de la materia' %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Actualizar Materia' %>
  </div>
    </div>
      </div>
      
<% end %>

<%= link_to 'Cancelar y volver a la lista', institution_subjects_path(@institution), class: 'button first' %>

app/views/subjects/index.html.erb
<!-- app/views/subjects/index.html.erb -->
<div class="card" >
  <div class="card-body wow-bg" id="formBg" >
<hr class="sin-color">

<h1>Materias de <%= @institution.name %></h1>
<div class="grid">
  <svg class="grid-svg" xmlns="http://www.w3.org/2000/svg" width="982" height="786" viewBox="0 0 982 786" fill="none">
    <path fill-rule="evenodd" clip-rule="evenodd" d="M490 401V537H348.5V401H490ZM490 785.5V676H348.5V785.5H347.5V676H206V785.5H205V676H63.5V785.5H62.5V676H0V675H62.5V538H0V537H62.5V401H0V400H62.5V258H0V257H62.5V116H0V115H62.5V0H63.5V115L205 115V0H206V115L347.5 115V0H348.5V115H490V0H491V115L627.5 115V0H628.5V115H765V0H766V115L902.5 115V0H903.5V115H982V116H903.5V257H982V258H903.5V400H982V401H903.5V537H982V538H903.5V675H982V676H903.5V785.5H902.5V676H766V785.5H765V676H628.5V785.5H627.5V676H491V785.5H490ZM902.5 675V538H766V675H902.5ZM902.5 537V401H766V537H902.5ZM902.5 400V258H766V400H902.5ZM902.5 257V116L766 116V257H902.5ZM627.5 675H491V538H627.5V675ZM765 675H628.5V538H765V675ZM348.5 675H490V538H348.5V675ZM347.5 538V675H206V538H347.5ZM205 538V675H63.5V538H205ZM765 537V401H628.5V537H765ZM765 400V258H628.5V400H765ZM765 257V116H628.5V257H765ZM347.5 401V537H206V401H347.5ZM205 401V537H63.5V401H205ZM627.5 401V537H491V401H627.5ZM627.5 116L491 116V257H627.5V116ZM627.5 258H491V400H627.5V258ZM63.5 257V116L205 116V257H63.5ZM63.5 400V258H205V400H63.5ZM206 116V257H347.5V116L206 116ZM348.5 116V257H490V116H348.5ZM206 400V258H347.5V400H206ZM348.5 258V400H490V258H348.5Z" fill="url(#paint0_radial_1_8)" />
    <defs>
      <radialGradient id="paint0_radial_1_8" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(491 392.75) rotate(90) scale(513.25 679.989)">
        <stop stop-color="white" stop-opacity="0.2" />
        <stop offset="1" stop-color="#000" stop-opacity="0" />
      </radialGradient>
    </defs>
  </svg>
  <div class="blur"></div>
</div>
</div>
</div>
<hr class="sin-color">
<hr class="sin-color">

<%= link_to 'Nueva Materia', new_institution_subject_path(@institution), class: 'button first' %>

<ul>
  <% @subjects.each do |subject| %>
    <li>
      <%= link_to subject.name, institution_subject_path(@institution, subject), class: 'button first' %>
    </li>
  <% end %>
</ul>

app/views/subjects/new.html.erb
<!-- app/views/subjects/new.html.erb -->
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">

<h1>Crea una Nueva Materia</h1>
<hr class="sin-color">
<hr class="sin-color">

<div class="grid">
  <svg class="grid-svg" xmlns="http://www.w3.org/2000/svg" width="982" height="786" viewBox="0 0 982 786" fill="none">
    <!-- Tu contenido SVG aquí -->
  </svg>
  <div class="blur"></div>
</div>

<div class="card" >
  <div class="card-body wow-bg" id="formBg" >


<%= form_with(model: [@institution, @subject], local: true) do |form| %>
  <% if @subject.errors.any? %>
        <div class="form-inputs">

    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> no se pudo guardar la materia</h2>

      <ul>
        <% @subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="color:white;">
    <%= form.label :name, 'Materia' %>
    <%= form.text_field :name %>
  </div>
<hr class="sin-color">

    <div class="field" style="color:white;">
    <%= form.label :teacher, 'Profesor' %>
    <%= form.select :teacher_id, options_for_select(@institution.teachers.map {|teacher| [teacher.name, teacher.id]}) %>
  </div>
 </div>
</div>
</div>
<hr class="sin-color">

<div class="form-actions">
 <button> <%= form.submit 'Guardar', class: "btn btn-outline-light btn-md" %> </button>
</div>

<% end %>

<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">



 <%= link_to 'Back to Institutions', institutions_path, class: "btn btn-outline-light btn-md" %>
</div>
</div>

app/views/subjects/show.html.erb
<!-- app/views/subjects/show.html.erb -->
<h1>Materia: <%= @subject.name %></h1>

<p>
  <strong>Nombre:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Editar', edit_institution_subject_path(@institution, @subject) %> |
<%= link_to 'Volver a la lista', institution_subjects_path(@institution) %>