config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :students
  devise_for :teachers, controllers: { sessions: 'teachers/sessions' }
  devise_for :institutions


  resources :institutions, only: [:new, :create, :show, :edit, :update, :destroy]
  root to: "pages#home"


  resources :institutions do
    resources :subjects, only: [:new, :create]
    resources :teachers, only: [:new, :create]
    resources :students, only: [:new, :create]
  end



  # nesteado para rutas de take_quizzes de un quiz
  # el alumno no puede borrar, editar o un quiz
  resources :quizzes do
    resources :take_quizzes, only: [:new, :create]
    end

  resources :teachers, only: [:new, :create, :show] do
    resources :quizzes
  end

  resources :quizzes do
    resources :take_quizzes, only: [:new, :create]
  end

  resources :students do
    resources :student_subjects, only: [:new, :create]
  end

  resources :questions, only: [:index, :show]

  get 'quienes_somos', to: 'pages#quienes_somos'
  get 'preguntas_frecuentes', to: 'pages#preguntas_frecuentes'

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  belongs_to :institution
  has_one :subject
end

app/controllers/teachers/sessions_controller.rb
# frozen_string_literal: true

class Teachers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    teacher_path(resource) # Redirige al show del profesor logueado
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_institution, only: [:new, :create]
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  def index
    @teachers = Teacher.all # or scope to institution if necessary
  end

  def show
    @subjects = @teacher.subject
    @students = Student.where(institution_id: @teacher.institution_id)
  end

  def new
    @teacher = @institution.teachers.new
  end

  def create
    @teacher = @institution.teachers.new(teacher_params)
    if @teacher.save
      redirect_to [@institution, @teacher], notice: 'El profesor se ha creado de manera exitosa.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to [@institution, @teacher], notice: 'El profesor ha sido actualizado de manera exitosa.'
    else
      render :edit
    end
  end

  def destroy
    @teacher.destroy
    redirect_to institution_teachers_url(@institution), notice: 'El profesor ha sido eliminado de manera exitosa.'
  end

  private

  def set_institution
    # @institution = Institution.find(params[:institution_id])
    @institution = Institution.find(1)
  end

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:name, :email, :password, :password_confirmation, :institution_id)
  end
end

app/views/teachers/edit.html.erb
<%= form_with model: @teacher do |f| %>
    
     <%= f.label :Nombre %>
    <%= f.text_field :name %>
    
    <%= f.label :Email %>
    <%= f.text_field :email %>
    
    <%= f.label :Password %>
    <%= f.text_field :password %>
       

    <%= f.submit "Actualizar" %>
<% end %>

app/views/teachers/new.html.erb
<h1>Crear un Nuevo Maestro</h1>
<hr class="sin-color">

<div class="grid">
  <svg class="grid-svg" xmlns="http://www.w3.org/2000/svg" width="982" height="786" viewBox="0 0 982 786" fill="none">
    <!-- Tu contenido SVG aquí -->
  </svg>
  <div class="blur"></div>
</div>

<div class="card" >
  <div class="card-body wow-bg" id="formBg" >

<%= form_with model: [@institution, @teacher] do |f| %>
<div class="form-inputs" style="color:white;">

    <%= f.label :Email %>
    <%= f.text_field :email %>

    <%= f.label :Password %>
    <%= f.password_field :password%>

    <%= f.label :Nombre %>
    <%= f.text_field :name %>
</div>
</div>
</div>

 <div class="form-actions">
  <button>  <%= f.submit "Registrar Maestro", class: "btn btn-outline-light btn-md" %> </button>
        </div>

<% end %>

app/views/teachers/show.html.erb
<%# app/views/teachers/show.html.erb %>
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">
<hr class="sin-color">






<div class="grid">
  <svg class="grid-svg" xmlns="http://www.w3.org/2000/svg" width="982" height="786" viewBox="0 0 982 786" fill="none">
    <!-- Tu contenido SVG aquí -->
  </svg>
  <div class="blur"></div>
</div>

<h1>Profesor: <%= @teacher.name %></h1>

<p>
  <strong>Correo Electrónico:</strong>
  <%= @teacher.email %>
</p>
<hr class="sin-color">

<div class="card">
  <div class="card-body wow-bg" id="formBg">
    <div class="container">
      <div class="row">
        <div class="col-6">
          <h5 style="color:white;">Mi Materia:</h5>
         <h5 style="color:white;"> <%= @teacher.subject.name %> </h5>
        </div>

        <div class="col-6">
          <h5 style="color:white;">Examenes</h5>
          <table class="table-dark">
            <thead>
              <tr>
                <th scope="col">Crear Examen</th>
                <th scope="col"><%= link_to '+', new_teacher_quiz_path(@teacher), class: "btn btn-outline-light btn-md" %></th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<hr class="sin-color">
<hr class="sin-color">

<div class="card">
  <div class="card-body wow-bg" id="formBg">
    <div class="row">
      <div class="col-6">
        <h4>Alumnos</h4>
        <table class="table-dark">
          <thead>
            <tr>
              <th scope="col">Nombre</th>
              <th scope="col">Correo</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @students.each do |student|  %>
              <tr>
                <td scope="row"><%= student.name %></td>
                <td scope="row"><%= student.email %></td>
                <td scope="row"><div class="btn-group" role="group" aria-label="Acciones">
          <%= link_to 'Ver', student_path(student), class:"btn btn-outline-light btn-md" %>
          <%= link_to 'Editar', edit_student_path(student), class: "btn btn-outline-light btn-md"%>
          <%= link_to 'Eliminar', student_path(student), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-outline-light btn-md" %>
        </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<hr class="sin-color">
<hr class="sin-color">
<%#= link_to 'Editar', edit_teacher_path(@teacher) %>
<%#= link_to 'Volver', teachers_path %>